name: NASA Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    env:
      CI: ""
      MONGO_URL: mongodb://localhost/nasaFranck
    strategy:
      matrix:
        node-version: [14.x, 23.x]
        mongodb-version: ['4.2', '4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version  ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Install dependencies
        run: |
          cd server
          npm ci 
      - run: npm install --prefix client
      - run: npm run build --prefix client
      - run: npm test

  